application: 20110406-munichjs
version: 1-0
runtime: python
api_version: 1

default_expiration: "365d"

handlers:

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /fonts
  static_dir: fonts

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*(css|js|gif|png|manifest|ico))
